version: '3.3'
services:
  wine:
    build: .
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./wine:/root/.wine
      - ./patch.sh:/patch.sh:ro
    command: >
      sh -c "
        wineboot --init &&
        winetricks dotnet35sp1 &&
        wine /chernobyl/installer/setup.exe &&
        sleep infinity
      "
