version: '3.3'
services:
  wine:
    build: .
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - WINEDLLOVERRIDES=
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./wine:/root/.wine32
      - ./patch.sh:/patch.sh:ro
    command: >
      sh -c "
        winetricks dotnet35sp1 &&
        wine /chernobyl/setup.exe &&
        sleep infinity
      "
